<a href="https://colab.research.google.com/github/aliciawill/python-data/blob/master/colab_test_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# csv파일을 colab linux에 업로드
# df로 읽어보세요.

In [ ]:
# csv파일을 google drive에 업로드
# colab + google drive mount
# df2로 읽어보세요.

In [2]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 39 not upgraded.
Need to get 9,604 kB of archives.
After this operation, 29.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 fonts-nanum all 20170925-1 [9,604 kB]
Fetched 9,604 kB in 1s (10.0 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package fonts-nanum.
(Reading database ... 155335 files and di

In [1]:
import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic') 

In [2]:
import pandas as pd
import numpy as np

In [3]:
dates = pd.date_range('20190301', periods=6)
dates

DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
np.random.randn(6,4)

array([[-0.31823954, -0.81313862, -0.76660498, -0.75380187],
       [ 0.88093634, -0.04029605, -0.40942749,  0.32690382],
       [ 0.94528539,  0.12100693,  1.01896193, -1.31000474],
       [-0.2877242 , -0.0187115 , -0.63038297, -0.26529142],
       [-1.73087803, -0.6172214 ,  0.5223089 ,  1.03155506],
       [ 1.64092532,  0.48838678,  1.09816433,  0.54701572]])

In [5]:
df = pd.DataFrame(np.random.randn(6,4), 
                  columns=['A', 'B', 'C', 'D'])
# df = pd.DataFrame(ndarray(values), columns=['컬럼명','컬럼명']) 
df

A         B         C         D
0  1.340973  0.890463 -0.007782 -0.020526
1  0.662358  0.450686 -0.256059  0.035671
2 -1.715075 -0.827274 -1.192735 -1.347866
3  0.298053 -0.778686 -0.025248  0.175458
4  1.851331  0.806033 -1.733749 -1.414071
5 -0.450250  1.194360  0.224527 -0.356142

In [6]:
df2 = pd.DataFrame(data = np.random.randn(6,4), 
                  index = dates, 
                  columns=['A', 'B', 'C', 'D'])
df2

A         B         C         D
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [7]:
type(df2)

pandas.core.frame.DataFrame

In [8]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [9]:
df2.index

DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')

In [10]:
in1 = df2.index
in1

DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
in1[0]

Timestamp('2019-03-01 00:00:00', freq='D')

In [12]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [13]:
in2 = df.index
in2

RangeIndex(start=0, stop=6, step=1)

In [14]:
in2[2] 
#리스트를 가지고 만든 여러가지 객체들은 리스트처럼 똑같이 다루어도 크게 문제가 발생하지는 않는다.

2

In [16]:
ts1 = in1[0]
ts1

Timestamp('2019-03-01 00:00:00', freq='D')

In [17]:
str(ts1)

'2019-03-01 00:00:00'

In [18]:
df['A']

0    1.340973
1    0.662358
2   -1.715075
3    0.298053
4    1.851331
5   -0.450250
Name: A, dtype: float64

In [20]:
type(df['A'])


pandas.core.series.Series

In [22]:
a = df['A']
a

0    1.340973
1    0.662358
2   -1.715075
3    0.298053
4    1.851331
5   -0.450250
Name: A, dtype: float64

In [23]:
a[0]

1.340972743757605

In [24]:
a[1]

0.6623576695400148

In [25]:
df2.values

array([[-0.86128148,  0.60995441,  1.17740596,  0.02678625],
       [ 0.76891669,  0.08861974,  0.15186121, -0.58592567],
       [ 0.31181982, -0.894816  ,  1.13740523, -0.72594341],
       [-0.51092542,  0.68838208,  1.27064683, -0.78059024],
       [-1.99807331, -0.12121387,  2.36560607,  0.26402922],
       [ 0.84678186,  0.99161771, -0.84254307, -0.73338558]])

In [26]:
df2.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.240460  0.227091  0.876730 -0.422505
std    1.100339  0.684550  1.096505  0.450964
min   -1.998073 -0.894816 -0.842543 -0.780590
25%   -0.773692 -0.068755  0.398247 -0.731525
50%   -0.099553  0.349287  1.157406 -0.655935
75%    0.654642  0.668775  1.247337 -0.126392
max    0.846782  0.991618  2.365606  0.264029

In [27]:
df2.sort_index() #df2.sort_index(ascending=True)

A         B         C         D
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [28]:
df2.sort_index(ascending=False)

A         B         C         D
2019-03-06  0.846782  0.991618 -0.842543 -0.733386
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-01 -0.861281  0.609954  1.177406  0.026786

In [29]:
df2.sort_values(by='A')

A         B         C         D
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [30]:
df2.sort_values(by='A', ascending=False)

A         B         C         D
2019-03-06  0.846782  0.991618 -0.842543 -0.733386
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-05 -1.998073 -0.121214  2.365606  0.264029

In [31]:
df2

A         B         C         D
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [32]:
df3 = df2.copy()
df3

A         B         C         D
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [33]:
# df3를 B로 정렬해주세요!
df3.sort_values(by='B')

# df3의 내용이 변경되어야 합니다.
df3 = df3.sort_values(by='B')
# df3.sort_values(by='B', inplace=True)와 동일
df3

A         B         C         D
2019-03-03  0.311820 -0.894816  1.137405 -0.725943
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [47]:
df3['A'] #df3.A

2019-03-03    1.000000
2019-03-05   -1.998073
2019-03-02    0.768917
2019-03-01   -0.861281
2019-03-04   -0.510925
2019-03-06    0.846782
Name: A, dtype: float64

In [49]:
df3['A'][0]

1.0

In [50]:
df3['A'].index

DatetimeIndex(['2019-03-03', '2019-03-05', '2019-03-02', '2019-03-01',
               '2019-03-04', '2019-03-06'],
              dtype='datetime64[ns]', freq=None)

In [51]:
df3['A'].values

array([ 1.        , -1.99807331,  0.76891669, -0.86128148, -0.51092542,
        0.84678186])

In [37]:
# 변경된 df3에서 b, c만 추출하여 df4로 저장
df3[['B', 'C']]

B         C
2019-03-03 -0.894816  1.137405
2019-03-05 -0.121214  2.365606
2019-03-02  0.088620  0.151861
2019-03-01  0.609954  1.177406
2019-03-04  0.688382  1.270647
2019-03-06  0.991618 -0.842543

In [38]:
# df3의 첫번째 행, 첫번째 열의 값을 1로 수정
df3.iloc[0, 0] = 1
df3.iloc[0, 0]

1.0

In [44]:
# df3에서 0행에서 2행까지 추출
df3.iloc[0:3] #df3.iloc[추출범위행] => 행으로 취급!
# df3.iloc[:,0:2] #df3.iloc[추출범위행, 추출범위열] => 열로 추출 가능!

A         B         C         D
2019-03-03  1.000000 -0.894816  1.137405 -0.725943
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-02  0.768917  0.088620  0.151861 -0.585926

In [39]:
# df3에서 2019-03-01, A열의 값을 추출
df3.loc['2019-03-01','A']

2019-03-01   -0.861281
Name: A, dtype: float64

In [52]:
type(df3.loc['2019-03-01','A'])

pandas.core.series.Series

In [41]:
# df3에서 2019-03-01, A열, B열의 값을 추출
df3.loc['2019-03-01',['A','B']]

A         B
2019-03-01 -0.861281  0.609954

In [42]:
# df3에서 A열의 전체 행을 추출
df3.loc[:, 'A']

2019-03-03    1.000000
2019-03-05   -1.998073
2019-03-02    0.768917
2019-03-01   -0.861281
2019-03-04   -0.510925
2019-03-06    0.846782
Name: A, dtype: float64

In [53]:
# df3에서 A, C열의 전체 행을 추출
df3.loc[:, ['A', 'C']]

A         C
2019-03-03  1.000000  1.137405
2019-03-05 -1.998073  2.365606
2019-03-02  0.768917  0.151861
2019-03-01 -0.861281  1.177406
2019-03-04 -0.510925  1.270647
2019-03-06  0.846782 -0.842543

In [54]:
type(df3.loc[:, ['A', 'C']])
# loc, iloc의 결과가 1행인 경우, Series로 리턴
# loc, iloc의 결과가 여러행인 경우, DataFrame으로 리턴

pandas.core.frame.DataFrame

In [ ]:
# A열의 값을 추출하여 2번째 값 추출
# => 결과가 1행인 경우, Series(list처럼 다루면 된다.)
# A열과 C열을 추출하여 1번째 행, 1번째 열의 값을 추출
# => 결과가 2행이상인 경우, DataFrame임.(df으로 다루면 된다.)

In [55]:
df3.loc[:, 'A']

2019-03-03    1.000000
2019-03-05   -1.998073
2019-03-02    0.768917
2019-03-01   -0.861281
2019-03-04   -0.510925
2019-03-06    0.846782
Name: A, dtype: float64

In [56]:
type(df3.loc[:, 'A'])

pandas.core.series.Series

In [57]:
df3.loc[:, 'A'][1]

-1.998073308449877

In [58]:
list(df3.loc[:, 'A'])

[1.0,
 -1.998073308449877,
 0.7689166850182734,
 -0.8612814786418684,
 -0.5109254245034733,
 0.8467818579303671]

In [59]:
df3.loc[:, 'A'].to_list()

[1.0,
 -1.998073308449877,
 0.7689166850182734,
 -0.8612814786418684,
 -0.5109254245034733,
 0.8467818579303671]

In [61]:
# df3에서 0번 행렬 추출
df3.iloc[0, :]

A    1.000000
B   -0.894816
C    1.137405
D   -0.725943
Name: 2019-03-03 00:00:00, dtype: float64

In [62]:
type(df3.iloc[0, :])

pandas.core.series.Series

In [63]:
# df3의 행렬의 크기를 추출
df3.shape

(6, 4)

In [64]:
df3.T

2019-03-03  2019-03-05  2019-03-02  2019-03-01  2019-03-04  2019-03-06
A    1.000000   -1.998073    0.768917   -0.861281   -0.510925    0.846782
B   -0.894816   -0.121214    0.088620    0.609954    0.688382    0.991618
C    1.137405    2.365606    0.151861    1.177406    1.270647   -0.842543
D   -0.725943    0.264029   -0.585926    0.026786   -0.780590   -0.733386

In [65]:
# df3에서 5행 전체 열 추출
df3.iloc[5]

A    0.846782
B    0.991618
C   -0.842543
D   -0.733386
Name: 2019-03-06 00:00:00, dtype: float64

In [66]:
# df3에서 4행부터 추출
df3.iloc[4:] #0~5

A         B         C         D
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [68]:
df3

A         B         C         D
2019-03-03  1.000000 -0.894816  1.137405 -0.725943
2019-03-05 -1.998073 -0.121214  2.365606  0.264029
2019-03-02  0.768917  0.088620  0.151861 -0.585926
2019-03-01 -0.861281  0.609954  1.177406  0.026786
2019-03-04 -0.510925  0.688382  1.270647 -0.780590
2019-03-06  0.846782  0.991618 -0.842543 -0.733386

In [67]:
# df3에서 0, 3행, 1부터 2열까지 추출
df3.iloc[[0, 3], [1, 2]]

B         C
2019-03-03 -0.894816  1.137405
2019-03-01  0.609954  1.177406

In [70]:
# df3에서 1,2,5행, 1,3열 추출
result1 = df3.iloc[[1,2,5], [1, 3]]
result1

B         D
2019-03-05 -0.121214  0.264029
2019-03-02  0.088620 -0.585926
2019-03-06  0.991618 -0.733386

In [71]:
type(result1)

pandas.core.frame.DataFrame

In [72]:
result1.index

DatetimeIndex(['2019-03-05', '2019-03-02', '2019-03-06'], dtype='datetime64[ns]', freq=None)

In [74]:
list(result1.index)

[Timestamp('2019-03-05 00:00:00'),
 Timestamp('2019-03-02 00:00:00'),
 Timestamp('2019-03-06 00:00:00')]