In [1]:
import pandas as pd

## train data 불러오기

In [2]:
train_df = pd.read_csv('./data_list/ratings_train.txt', encoding='utf8', sep='\t', engine='python')
train_df

id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        150000 non-null  int64 
 1   document  149995 non-null  object
 2   label     150000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [4]:
train_df = train_df[train_df['document'].notnull()]
train_df

id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[149995 rows x 3 columns]

In [5]:
import re
import warnings
warnings.filterwarnings(action='ignore')

In [6]:
train_df['document'] = train_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', '', x))
train_df['document'][:5]

0                                    아 더빙 진짜 짜증나네요 목소리
1                           흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나
2                                    너무재밓었다그래서보는것을추천한다
3                            교도소 이야기구먼 솔직히 재미는 없다평점 조정
4    사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...
Name: document, dtype: object

## test data 불러오기

In [7]:
test_df = pd.read_csv('./data_list/ratings_test.txt', encoding='utf8', sep='\t', engine='python')
test_df

id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[50000 rows x 3 columns]

In [8]:
test_df = test_df[test_df['document'].notnull()]
test_df

id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[49997 rows x 3 columns]

In [9]:
test_df['document'] = test_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', '', x))
test_df['document'][:5]

0                                          굳 ㅋ
1                                             
2             뭐야 이 평점들은 나쁘진 않지만 점 짜리는 더더욱 아니잖아
3                    지루하지는 않은데 완전 막장임 돈주고 보기에는
4    만 아니었어도 별 다섯 개 줬을텐데 왜 로 나와서 제 심기를 불편하게 하죠
Name: document, dtype: object

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from konlpy.tag import Okt

In [11]:
okt = Okt()

In [12]:
tfidf = TfidfVectorizer(tokenizer = okt.morphs,
                        ngram_range=(1, 2),
                        min_df = 3,
                        max_df = 0.9)
tfidf

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x000001AA1740AB70>>)

- max_df : 정수 또는 [0.0, 1.0] 사이의 실수. 디폴트 1   
최대 몇개 문서에 걸쳐 포함된 단어까지 단어 꾸러미에 담아 사용할 것인지
- min_df : 정수 또는 [0.0, 1.0] 사이의 실수. 디폴트 1   
최소 몇개 문서에 걸쳐 포함된 단어를 단어 꾸러미에 담아 사용할 것인지
- ngram-range(1,2): 한글자가 따로 나오거나, 두 글자가 같이 나오는 빈도수의 matrix

In [13]:
tfidf.fit(train_df['document'])

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x000001AA1740AB70>>)

사전 만들때나, 스케일링시 fit()시킬 때, 반드시  train데이터를 사용한다.!   
test 데이터만을 가지고 fit()시키지 않는다.!

In [14]:
train_tfidf_df = tfidf.transform(train_df['document'])
train_tfidf_df

<149995x115612 sparse matrix of type '<class 'numpy.float64'>'
	with 2703859 stored elements in Compressed Sparse Row format>

df의 컬럼으로 들어갈 수 있도록 one-hot encoding하는 것.(DTM만드는 중)

In [15]:
test_tfidf_df = tfidf.transform(test_df['document'])
test_tfidf_df

<49997x115612 sparse matrix of type '<class 'numpy.float64'>'
	with 871912 stored elements in Compressed Sparse Row format>

In [16]:
tfidf.inverse_transform(train_tfidf_df)

[array(['짜증나네요', '진짜 짜증나네요', '진짜', '아', '목소리', '더빙 진짜', '더빙'], dtype='<U30'),
 array(['흠', '포스터 보고', '포스터', '초딩 영화', '초딩', '줄', '조차', '오버 연기', '오버',
        '영화 줄', '영화', '연기 조차', '연기', '않구나', '보고', '가볍지'], dtype='<U30'),
 array(['한 다', '한', '추천 한', '추천', '보는것을 추천', '보는것을', '무재', '래서', '다그', '다',
        '너 무재', '너'], dtype='<U30'),
 array(['평점 조정', '평점', '조정', '재미 는', '재미', '이야기', '없다 평점', '없다', '솔직히 재미',
        '솔직히', '는 없다', '는', '구먼', '교도소'], dtype='<U30'),
 array(['했던', '커스틴', '이뻐', '의', '영화', '연기 가', '연기', '에서', '스파이더맨', '사이',
        '보였다', '돋보였던 영화', '돋보였던', '늙어', '너무나도', '그 의', '그', '가 돋보였던',
        '가 너무나도', '가'], dtype='<U30'),
 array(['학년', '초등학교 학년', '초등학교', '움', '영화 ㅋㅋㅋ', '영화', '아까 움', '아까', '세',
        '생인', '부터', '별 반개', '별', '반개 도', '반개', '막', '마', '뗀', '도 아까', '도',
        '걸음', 'ㅋㅋㅋ 별', 'ㅋㅋㅋ'], dtype='<U30'),
 array(['했다', '제대로', '의 긴장감', '의', '을 제대로', '을', '원작 의', '원작', '긴장감 을',
        '긴장감'], dtype='<U30'),
 array(['해도 그것', '해도', '하는 사람', '하는', '정말', '인지 정말', '

In [17]:
tfidf.inverse_transform(test_tfidf_df)

[array(['굳 ㅋ', '굳', 'ㅋ'], dtype='<U30'),
 array([], dtype='<U30'),
 array(['평점 들', '평점', '짜 리', '짜', '점 짜', '점', '이 평점', '이', '은', '야 이', '야',
        '않지만', '아니잖아', '뭐 야', '뭐', '리 는', '리', '들 은', '들', '더욱', '더 더욱',
        '더', '는 더', '는', '나쁘진 않지만', '나쁘진'], dtype='<U30'),
 array(['지루하지는', '주고 보기', '주고', '임 돈', '임', '완전 막장', '완전', '에는', '않은데',
        '보기 에는', '보기', '막장 임', '막장', '돈 주고', '돈'], dtype='<U30'),
 array(['하죠', '줬을텐데', '제', '왜', '아니었어도', '심기', '불편하게', '별 다섯', '별',
        '만 아니었어도', '만', '를', '로 나와서', '로', '다섯 개', '다섯', '나와서', '개'],
       dtype='<U30'),
 array(['최고 의', '최고', '주가', '이', '의 음악', '의', '음악 이', '음악 영화', '음악', '영화',
        '된 최고', '된'], dtype='<U30'),
 array(['진정한 쓰레기', '진정한', '쓰레기'], dtype='<U30'),
 array(['한다', '한', '창의력', '젖게', '에서', '없는', '애니 에서', '애니', '부터가', '미국 애니',
        '미국', '마치', '를', '로봇', '디자인', '고개 를', '고개'], dtype='<U30'),
 array(['폼', '중국영화', '잡다', '이다', '이건 류', '이건', '유치한', '유치하고 내용', '유치하고',
        '영화 가', '영화', '에 유치한', '에', '없음', '안되는', '

In [18]:
from sklearn.linear_model import LogisticRegression

SA_lr = LogisticRegression(random_state = 0)

In [19]:
SA_lr.fit(train_tfidf_df, train_df['label'])

LogisticRegression(random_state=0)

In [20]:
test_predict = SA_lr.predict(test_tfidf_df)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
print('감성 분석 정확도 : ', round(accuracy_score(test_df['label'], test_predict), 3))

감성 분석 정확도 :  0.852


In [23]:
st = "웃자 ^o^ 오늘은 좋은 날이 될 것 같은 예감100%! ^^*"

In [24]:
st2 = re.sub(r'[^ ㄱ-ㅎ|가-힣]+', "", st)
st2

'웃자  오늘은 좋은 날이 될 것 같은 예감 '

In [25]:
st_tfidf_df = tfidf.transform([st2])
st_tfidf_df

<1x115612 sparse matrix of type '<class 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [26]:
st2_predict = SA_lr.predict(st_tfidf_df)
st2_predict, st2_predict[0]

(array([1], dtype=int64), 1)

In [27]:
if(st2_predict[0] == 0):
    print(st2, '==> 부정 감정')
else:
    print(st2, '==> 긍정 감정')

웃자  오늘은 좋은 날이 될 것 같은 예감  ==> 긍정 감정


In [28]:
st3 = "짱나! 진짜야"

In [29]:
st4 = re.sub(r'[^ ㄱ-ㅎ|가-힣]+', "", st3)
st4

'짱나 진짜야'

In [30]:
# 1) 입력 텍스트의 피처 벡터화
st4_tfidf = tfidf.transform([st4])

# 2) 최적 감성분석 모델에 적용하여 감성 분석 평가
st4_predict2 = SA_lr.predict(st4_tfidf)

In [31]:
st4_predict2[0]

0

In [32]:
if(st4_predict2[0] == 0):
    print(st3, '==> 부정 감정')
else:
    print(st3, '==> 긍정 감정')

짱나! 진짜야 ==> 부정 감정


In [33]:
import pickle
import joblib

In [34]:
tfidf_fit = tfidf.fit(train_df['document'])
tfidf_fit

TfidfVectorizer(max_df=0.9, min_df=3, ngram_range=(1, 2),
                tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x000001AA1740AB70>>)

In [35]:
saved_model = pickle.dumps(SA_lr)

In [36]:
lr_from_pickle = pickle.loads(saved_model)
lr_from_pickle.predict(st_tfidf_df[0])

array([1], dtype=int64)

In [37]:
joblib.dump(SA_lr, 'movie_SA_lr.pkl')

['movie_SA_lr.pkl']

In [38]:
lr_from_joblib = joblib.load('movie_SA_lr.pkl')
lr_from_joblib

LogisticRegression(random_state=0)

In [39]:
lr_from_joblib.predict(st_tfidf_df[0])

array([1], dtype=int64)