In [10]:
import tensorflow

In [3]:
tensorflow.__version__

'2.7.0'

In [11]:
#!pip install tensorflow==2.7.0

In [1]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [2]:
model = Sequential()

2022-06-02 17:49:57.232438: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
model.add(Dense(units=1, activation='linear', input_dim=1))
model.add(Dense(units=1, activation='linear', input_dim=1))
model.add(Dense(units=1, activation='linear', input_dim=1))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
 dense_2 (Dense)             (None, 1)                 2         
                                                                 
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.4183793]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.4731365]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.215377]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [10]:
model.predict([[1],[2],[5]])

array([[-0.7490731],
       [-1.4981462],
       [-3.7453656]], dtype=float32)

In [11]:
from sklearn import datasets
boston = datasets.load_boston()
X_data = boston.data

In [12]:
y_data = boston.target

In [13]:
print(X_data.shape, y_data.shape)

(506, 13) (506,)


In [14]:
y_data[:3]

array([24. , 21.6, 34.7])

In [16]:
X_data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [20]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [21]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [29]:
## 전처리
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler()
x_data_min_max = min_max.fit_transform(X_data)
x_data_min_max[0]

array([0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
       0.57750527, 0.64160659, 0.26920314, 0.        , 0.20801527,
       0.28723404, 1.        , 0.08967991])

In [30]:
## 딥러닝 모델 만들어서
model2 = Sequential()
model2.add(Dense(128, activation='relu', input_dim=13))
model2.add(Dense(64, activation='relu'))
model2.add(Dense(1, activation='linear'))

In [31]:
## 위에 쌓은 모델로 설정해주세요.
model2.compile(optimizer='adam', loss='mse', metrics=['mae'])
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 128)               1792      
                                                                 
 dense_4 (Dense)             (None, 64)                8256      
                                                                 
 dense_5 (Dense)             (None, 1)                 65        
                                                                 
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________


In [34]:
## 공부시키고
model2.fit(x_data_min_max[:400], y_data[:400], epochs=3, batch_size=50, verbose=2)

Epoch 1/3
8/8 - 0s - loss: 178.5487 - mae: 10.5034 - 7ms/epoch - 835us/step
Epoch 2/3
8/8 - 0s - loss: 131.2215 - mae: 8.5907 - 8ms/epoch - 1ms/step
Epoch 3/3
8/8 - 0s - loss: 122.0128 - mae: 8.3423 - 7ms/epoch - 832us/step


In [35]:
## 정확도 계산
model2.evaluate(x_data_min_max[400:], y_data[400:])

4/4 [==============================] - 0s 1ms/step - loss: 280.2083 - mae: 15.4211


[280.208251953125, 15.421131134033203]

In [ ]:
## 예측